blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/mat-0/cheltenham-open-data/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/mat-0/cheltenham-open-data/security/advisories/new
    about: Report security vulnerabilities privately
